### ISSUE TITLE
ENV for country arguments

### ISSUE THREAD

**Issue by Magic-Unique** [majd/ipatool#103]
### Description

Add IPATOOL_COUNTRY to environment to auto set this value when use ipatool.

**Comment by majd** [comment]
I am generally against the idea of using environment variables in place of CLI arguments. The only reason `IPATOOL_EMAIL`, `IPATOOL_PASSWORD` and `IPATOOL_2FA_CODE` environment variables exist is to make it easier to use ipatool with automation as the tool would otherwise require an interactive session for accepting those inputs.
