### ISSUE TITLE
ipatool does not exist in brew package manager

### ISSUE THREAD

**Issue by mutairibassam** [majd/ipatool#127]
### What happened?

I am not able to find ipatool in brew package manager.

### Version

n/a

**Comment by majd** [comment]
Are you referring to Homebrew running on a specific operating system? I currently only distribute the tool for macOS using Homebrew.

You can install it by following the instructions in the readme.
https://github.com/majd/ipatool#package-manager-macos

**Comment by majd** [comment]
> I tried to search for ipatool package but didn't find it. Please refer to the below screenshot.

You can't find it on the homebrew website because it's not part of the default tap. That's why you need to add the tap `majd/repo` before installing the tool.

```
$ brew tap majd/repo
$ brew install ipatool
```

> A follow up question, can I install any ipa file or only what I am authenticated to?

You can install the ipa file as long as its signature is still valid - but you won't be able to launch it unless if the device can authenticate with the Apple ID that downloaded the app.

**Comment by mutairibassam** [comment]
I faced difficulties when I was trying to find an id identifier for an application which already exist in app store. So, I believe some people have faced it. 

I'd recommend to put the way of extracting id identifier in project readme to let everyone knows the way.

---
1. First navigate to the app that you want to install and check its url.

![image](https://user-images.githubusercontent.com/54819958/208076031-c2f7589b-39ba-4f2b-8301-a7a6f7724234.png)

2. Extract app id and country code from the above url and replace them with the below variables.
```js
`https://itunes.apple.com/lookup?id=${id}&country=${country}`
```
Example: https://itunes.apple.com/lookup?id=304158842&country=us

This will prompt you to download a text file which will have a bunch of values. The one you should be interested in is bundleid.

![image](https://user-images.githubusercontent.com/54819958/208076961-04fe6857-efb5-4a5f-9359-e1d991f52aff.png)


Credit goes to: (https://mrvirk.com/) - https://mrvirk.com/how-to-find-app-bundle-id-ios.html

**Comment by mutairibassam** [comment]
Issue:
I was able to point to a valid app id in different stores but all result to the same error.

<img width="1668" alt="Screen Shot 1444-05-22 at 1 22 27 PM" src="https://user-images.githubusercontent.com/54819958/208077699-8de8330a-4798-4b01-af5e-6eebc914bed3.png">

What is the need of the authentication part? Does the country should be similar?

For example: my account is from china and I am installing app from US store. Is this valid scenario?

**Comment by majd** [comment]
> What is the need of the authentication part?

You need to be authenticated in order to download and purchase apps from your App Store account. I think that's self explanatory.

> Does the country should be similar?

I'm not sure what you exactly mean by this but the tool uses the country code based on the account that you authenticated with.

> Does the tool support macOS and iPad?

The tool is for downloading iOS apps (including iPadOS) but not macOS.


FYI, you can also just use the `ipatool search ...` command to get the bundle identifier of the app.
