### ISSUE TITLE
Allow search without auth

### ISSUE THREAD

**Issue by sobolewska** [majd/ipatool#130]
### Description

I'm using ipatool in automation job run. 
Before v2.0 we could simply search app-store without any auth. 
Now with forced auth, we are unable to use ipatool as executing TFA in remote job is complex.
Can there be option to search with providing country / etc, but without auth?

**Comment by majd** [comment]
This is a deliberate decision that I went with to improve the customer experience. Providing a way to search by specifying the country code without authentication can lead to a situation where the user may be able to search for an app that is not possible to download with the tool, since the account may be in a different country.

I would recommend that you instead interact with the iTunes API directly in the case where you can't authenticate with `ipatool`.

```bash
$ curl -s 'http://itunes.apple.com/search?term=TestFlight&media=software&country=US' | jq -r '.results | first | .trackName'
TestFlight
```
