### ISSUE TITLE
Selection country

### ISSUE THREAD

**Issue by dayanch96** [majd/ipatool#166]
### Description

Hi. If it possible on go, can you add country selection as it was in previous versions? (-c, --country) Thanks

**Comment by dayanch96** [comment]
also, noticed that windows version doesn't work until you add extension **ipatool** => **ipatool.exe**

**Comment by majd** [comment]
You can only use ipatool to download apps that are available in the country of the App Store account. It's not possible to use a different store frontend than the one that is set for your Apple ID. The tool determines the country code based on the Apple ID you authenticate with. Allowing specifying the country would have no effect since the tool won't be able to download the app anyway.

**Comment by majd** [comment]
Releases from [2.0.3](https://github.com/majd/ipatool/releases/tag/v2.0.3) and onwards will have the `exe` extension for windows builds.
