### ISSUE TITLE
Download Error IPA

### ISSUE THREAD

**Issue by furkan-enes-polatoglu** [majd/ipatool#184]
### What happened?

10:05PM ERR error="failed to download file: license is required" success=false

Why this error?

### Version

last version

**Comment by majd** [comment]
You need to own a license for the app you are attempting to download. If the app is free, you can obtain a license using ipatool by using the `purchase` command or setting the `--purchase` flag when using the `download` command.

**Comment by sathiyapriyanofficial** [comment]
# Resolving "License is Required" Error in ipatool

When using [`ipatool`](https://github.com/majd/ipatool), you might encounter the following error:

```
Error: license is required
```

This happens because `ipatool` requires a valid license linked to your Apple ID for any app you download — even free apps.

---

## Steps to Resolve

### 1. Search for the App
Make sure the app exists and is available for your account.

```
ipatool search --limit 1 app_name
```

> **Note:**  
> The app must have been "purchased" or downloaded at least once on your Apple ID.  
> If you don’t have an iPhone (only a Mac), proceed to Step 2.

---

### 2. Obtain a License (Using Purchase Command)
Use the `purchase` subcommand to get a license, even for free apps.

```
ipatool purchase --bundle-identifier com.ubercab.UberClient
```

---

### 3. Download the IPA with the `--purchase` Flag
Once the license is attached to your Apple ID, download the app:

```
ipatool download --bundle-identifier net.whatsapp.WhatsApp --output WhatsApp.ipa --purchase
```

---

## Why This Happens
`ipatool` interacts with the App Store to fetch `.ipa` files. The App Store requires a valid license before allowing the download — this applies to both **paid** and **free** apps.  
Running `purchase` ensures a license is registered to your Apple ID, making the download possible.

---

## Tips & Troubleshooting
- Always log in with a valid Apple ID in `ipatool` before running these commands.
- For multiple apps, repeat the **purchase** step for each bundle identifier.
- Example for multiple apps:
    ```
    ipatool purchase --bundle-identifier com.twitter.ios
    ipatool purchase --bundle-identifier com.facebook.Facebook
    ```
- If you still see the error, try logging out and back into `ipatool`:
    ```
    ipatool auth revoke
    ipatool auth login
    ```

**Comment by zymawy** [comment]
So basically I cannot download any app that does not support my account country?
