### ISSUE TITLE
Sorry this is absolutely useless project.

### ISSUE THREAD

**Issue by vadimszzz** [majd/ipatool#24]
## [Error] Your Apple ID does not have a license for this app. Download the app on an iOS device to obtain a license.

Thanks for your work, you've reverse engineered gsa.apple.com auth and 2FA APIs. But what is this? This project makes no sense if I must hit "get" in the App Store on every app before using ipatool.

**Comment by vadimszzz** [comment]
I'll try to implement this feature and close the issue this week.

**Comment by PokemonHacker1337** [comment]
You know, you could have said most of what you said without being rude about it. While help is always appreciated, you don't have to be rude. Just say that you plan on implementing the buying/owning process and that's all you needed to do.

**Comment by vadimszzz** [comment]
> You know, you could have said most of what you said without being rude about it. While help is always appreciated, you don't have to be rude. Just say that you plan on implementing the buying/owning process and that's all you needed to do.

Sorry girl

**Comment by PythonicNinja** [comment]
@vadimszzz do it yourself as PR if "It's not so hard.". Contribute to opensource!

**Comment by vadimszzz** [comment]
> @vadimszzz do it yourself as PR if "It's not so hard.". Contribute to opensource!

Doing right now 👍

**Comment by blesio** [comment]
> ## [Error] Your Apple ID does not have a license for this app. Download the app on an iOS device to obtain a license.
> Thanks for your work, you've reverse engineered gsa.apple.com auth and 2FA APIs. But what is this? This project makes no sense if I must hit "get" in the App Store on every app before using ipatool.

You need to learn that everything you write before “but” is actually not true. Either you need to get some manner lessons or if you don’t like the project make your own which suits your needs and not bash other devs for doing great work. Because the project doesn’t make sense for you it doesn’t mean it doesn’t for others. You know why? Because most ppl own the apps so they don’t need to press Get before using this tool. Or is all this too hard for you to comprehend? It’s very easy to be an ahole. If it’s so easy for you why haven’t you reverse engineered what the dev did yourself? It’s bullcrap like this that discourages ppl and just plain hate. You should get reported

**Comment by vadimszzz** [comment]
@blesio nobody asked your opinion
