### ISSUE TITLE
Search doesnt find specific app

### ISSUE THREAD

**Issue by MikePendo** [majd/ipatool#269]
### What happened?

I wanted to find that app: https://apps.apple.com/us/app/communicate-by-smokeball/id1447059340
I had run the following:
ipatool search "Communicate By Smokeball"
ipatool search "communicate-by-smokeball"
I am on us store 
`ipatool search <term> [flags]` I used the app name in the <term> 

### Version

 2.1.3

### Relevant log output

```shell
ipatool search "Communicate By Smokeball" --verbose
INF apps=[] count=0
```

**Comment by zebooka** [comment]
It depends on you account region. I have compiled myself ipatool with US region hardcoded, because of some apps not available in my country because of sanctions. Although I can download and update them on iPhone, I can't do this via tool, because prior to downloading it tries to get app information using country code and could not find them.

So with your app and US region hardcoded:
```
$ ipatool-us search --format json "Communicate By Smokeball" | jq
{
  "level": "info",
  "count": 1,
  "apps": [
    {
      "id": 1447059340,
      "bundleID": "com.smokeball.communicate.nova",
      "name": "Communicate By Smokeball",
      "version": "3.499.0",
      "price": 0
    }
  ],
  "time": "2024-04-11T17:21:29+07:00"
}
```

**Comment by MikePendo** [comment]
That's strange as my account is on US
