### ISSUE TITLE
下载显示An unknown error has occurred

### ISSUE THREAD

**Issue by zwsn** [majd/ipatool#64]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/42889307/161202085-b2f18cce-dd81-417b-8d65-4206cad8f527.png">
还有能否默认搜索下载ID设置国家的应用,每次要指定有点麻烦

**Comment by majd** [comment]
I think you have a typo in the `download` command. You specified `EN` as the country but you probably meant `CN`. `EN` is not a valid ISO 3166-1 alpha-2 country code.

**Comment by ryh** [comment]
@zwsn the Default country code is `US` 默认的国家码是US 作者告诉你了EN不是国家码
Try alias the command with 你可以试试使用alias别名来使用
```
alias ipas="ipatool search -c CN "
ipas 六龙争霸
```
@majd  he was saying  that input a country every  search is kind of inconvenient. 

I would suggest a `ProcessInfo.processInfo.environment["IPATOOL_COUNTRY"]` for user setting their default country code, since alias needed to be set for every ipatool subcommand to work properly.

**Comment by zwsn** [comment]
看到了,我贴图的时候输错了,贴图之前一直使用的-c cn,找到问题所在了,是那个应用被下架了.
